### PR TITLE
create container.yaml for odcs multi-arch build

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch build
@dorzel @adammhaile Please review.

### CODE REVIEW

**Comment by adammhaile** [comment]
+1

**Comment by dorzel** [comment]
+1

**Comment by jeffdyoung** [comment]
@sjenning I'm not sure if you can approve, saw you approved the last PR. :)
We need to get this in, so @adammhaile can enable ppc64le builds for OCP. Thanks!

**Comment by jeffdyoung** [comment]
Dropping this. We won't be doing odcs builds in the near future. Thanks!

**Pull request closed without merging**
